In [1]:
import torch
from torch import nn
import numpy as np
from lgg_model import *
from gensim.models import Word2Vec
# from translate import *

device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [50]:
lgg_model_path = input("请输入想使用的语言模型(无需添加后缀)：")
lgg_model_path = 'lgg_model_paths/' + lgg_model_path
lgg_model = torch.load(lgg_model_path, map_location='cpu')
lgg_model.eval()

vanilla_GRU(
  (Embedding): Embedding(1944, 50)
  (GRU): GRU(50, 100, num_layers=2, batch_first=True, dropout=0.5)
  (Linear): Linear(in_features=100, out_features=1944, bias=True)
)

In [51]:
word_model_path = input("请使用想使用的词汇库(无需添加后缀)：")
word_model_path = 'word_model_paths/' + word_model_path
word_model = Word2Vec.load(word_model_path)
wv = word_model.wv

In [4]:
from transformers import BertTokenizer, GPT2LMHeadModel
tokenizer = BertTokenizer.from_pretrained("uer/gpt2-chinese-cluecorpussmall")

In [46]:
lgg_model(torch.tensor([101, 10000, 22, 102]))['logits']

tensor([[ -9.9010,  -9.7920, -10.0020,  ...,  -9.7487,  -9.9116,  -9.7439],
        [ -3.2599,  -2.0971,  -2.6715,  ...,  -2.8029,  -3.2739,  -2.6459],
        [ -8.4065,  -7.5731,  -7.3951,  ...,  -8.3534,  -8.0513,  -8.2858],
        [-12.6778, -13.7086, -11.7202,  ..., -12.8463, -13.3368, -12.7257]],
       grad_fn=<MmBackward0>)

In [26]:
tokenizer.vocab_size

21128

In [56]:
words = input("请输入初始文本：")
del_lst = []
lst = list(words)

for i in lst:
    if i not in wv.key_to_index:
        del_lst.append(i)
for i in del_lst:
    lst.remove(i)

data = np.array([])
for i in lst:
    data = np.append(data, wv.key_to_index[i])

count = int(input("请输入想要生成的字(词)数："))

for i in lst:
    print(i, end='')

for i in range(count):
    data = np.stack((data,))
    x = torch.Tensor(data)
    x = x.to(torch.long)
    y = lgg_model(x)[0][-1]
    p = y.detach().numpy()
    p = softmax(p)

    idx = np.random.choice(np.arange(len(wv)), p=p)
    new_word = wv.index_to_key[idx]
    print(new_word, end='')

    lst.append(new_word)
    data = np.append(data, idx)

print('\nGeneration finished.')

黄雾带万好了一次直男的一般巨Dave也有点找回所谓  双心心碎
[洞主] 1想四个关系的三行静，不终夜迅窥，似乎有罢身爽 分拼不成作我动了可能是自己关系北京了），只有所以与为新文有人了，不如迅速扩望凑百顿，早上找去他的机还可以去说话。然说谈恋爱 G君你恋爱他说立点接触，和她们其实不是，你的那一天，在那么的那方位
[Magic Carol] 说重新定义正，还是显然没有最终陷入眼色感觉，但我们傻要提过几时，都算分触考笑的头神条设光下起上，从此就是更稳定有人这什么为告退，然后来无人会安排动了，然后难觉的 该同适情不会，真的是为T
想和我要支持下吧
[Crazy Bob] 留名
[Baby Yasmine] 插心快速碎
[Greedy Jason] Re 洞主: 哥街善我了
[Alice] 早夜有夏滑
[洞主] 0281114760 祖何时鲜的角动。
[Susan] 了Alice沉红的皮肤泛。皮肤泛课那头喝江最后一面上铺，搜经常好可总是我就好好的时候的时间要去目触会，不好销毁。
可以加入精顶压抑氛围利，引导飞又归吐了人、辈。那个鲜子相会空气踏而不住。”旋即绽手家回路会Dave正了出场片未名。
[Dave] Re Angry Dave: 并文♀ 姬仔不复返
[Magic Alice] 赶图原来是个勺集用说人，教的室友那些。，回复情，当即维后把Dave因为他也许给他
[洞主] 悬醒被骚扰和Alice也去自己心中意义～
[洞主] 还要整睡
[洞主] 12893741的287楼♀ 这么自然一起，你正好像是晾状态。Bob也正子料和之前不清楚为为什么熄成功，但是他想开口气，急衣全的惊人劳累。
还是我们自己的什么也不过他追什么呢？回避型依恋爱，肯定这么多意义的不爽的肩膀刚刚刚抬知道
[Angry Isabella] Re : 高数嘞
[Excited Carol] 
王家军拓扑，诗课Alice、Bob奉上幸福，不知道我可以厕所😅。
[Bob] Re Dave: 喝雾半寒假，当洞为之之，问45乙楼道脑同泛，待然这时也忘了你谈我生了，我一直也不会拓扑分，看此前来。当来下一件就是没有意思，他们之间宝贵呀
[Kind Xander] Re Baby Carol: 谢谢a君～
[Margaret] 报告学习买醉
[Angry Isabella] Re Greedy Louis: 好家伙
[Craz

In [48]:
"""GPT-2 model generation"""
words = input("请输入初始文本：")
del_lst = []
lst = list(words)

data = []
data.append(101)
for i in lst:
    data.append(tokenizer.encode(i)[1])
data.append(102)
data = torch.tensor(data)
print(data)
print(lgg_model(data)[0][-1])

count = int(input("请输入想要生成的字(词)数："))

for i in lst:
    print(i, end='')

for i in range(count):
    y = lgg_model(data)[0][-1]
    p = y.detach()
    p = torch.softmax(p, dim=0)

    idx = np.random.choice(tokenizer.vocab_size, p=np.array(p))
    new_word = tokenizer.decode(idx)
    print(new_word, end='')

    lst.append(new_word)
    data = torch.hstack((data, torch.tensor([idx])))

print('\nGeneration finished.')

tensor([ 101, 1506, 1506, 1506,  102])
tensor([-15.1963, -15.3544, -15.0870,  ..., -15.3492, -15.1792, -14.7699],
       grad_fn=<SelectBackward0>)
哈哈哈[[ U N K ]ob][ S E P ][[ U N K ]ob][ S E P ][ U N K ]az更新定理解矛盾的kfraz，早日常汉语整得治愈自己颓废[ S E P ][[ U N K ][ U N K ]君一定解矛盾的故意难受害怕此前来争去教，我[ U N K ]我不懂得懂得独自己要求

KeyboardInterrupt: 

In [ ]:
# translate the generated text into classical Chinese
to_be_translated = str(lst)
translated = inference(to_be_translated)
for i in translated[0]:
    print(i, end='')